### ISSUE TITLE
DMNS Marine Invertebrate Collection (Arctos)

### ISSUE THREAD

**Issue by it-iode** [iobis/obis-network-datasets#10]
- title: DMNS Marine Invertebrate Collection (Arctos)
- GBIF: https://www.gbif.org/dataset/5a6977c1-ece6-44b8-b71d-43cb1d4e0919
- created: '2014-11-19T17:24:30.334+00:00'
- URLs:
  - http://ipt.vertnet.org:8080/ipt/resource?r=dmns_inv
  - http://ipt.vertnet.org:8080/ipt/resource.do?r=dmns_inv

**Comment by albenson-usgs** [comment]
As OBIS-USA node manager I endorse this dataset for publishing to OBIS.

**Comment by pieterprovoost** [comment]
Added to OBIS, thanks @albenson-usgs! https://obis.org/dataset/4a606f86-2e7b-44a3-b50d-3d55a887a11f
