### ISSUE TITLE
KUBI Ichthyology Collection

### ISSUE THREAD

**Issue by it-iode** [iobis/obis-network-datasets#11]
- title: KUBI Ichthyology Collection
- GBIF: https://www.gbif.org/dataset/8f79c802-a58c-447f-99aa-1d6a0790825a
- created: '2012-06-25T16:10:32.000+00:00'
- URLs:
  - http://ipt.nhm.ku.edu:8080/ipt/resource?r=kubi_ichthyology
  - http://ipt.nhm.ku.edu/ipt/resource?r=kubi_ichthyology
  - http://ipt.nhm.ku.edu/ipt/resource.do?r=kubi_ichthyology

**Comment by pieterprovoost** [comment]
Should I go ahead and remove https://www1.usgs.gov/obis-usa/ipt/resource?r=kubi_ichthyologycollection_marine from OBIS?
