### ISSUE TITLE
KUBI Ichthyology Tissue Collection

### ISSUE THREAD

**Issue by it-iode** [iobis/obis-network-datasets#12]
- title: KUBI Ichthyology Tissue Collection
- GBIF: https://www.gbif.org/dataset/56caf05f-1364-4f24-85f6-0c82520c2792
- created: '2012-06-25T16:10:15.000+00:00'
- URLs:
  - http://ipt.nhm.ku.edu:8080/ipt/resource?r=kubi_ichthyology_tissue
  - http://ipt.nhm.ku.edu/ipt/resource?r=kubi_ichthyology_tissue
  - http://ipt.nhm.ku.edu/ipt/resource.do?r=kubi_ichthyology_tissue

**Comment by albenson-usgs** [comment]
As OBIS-USA node manager I endorse this dataset for publishing to OBIS.
