### ISSUE TITLE
CAL Mammalogy not picked up?

### ISSUE THREAD

**Issue by albenson-usgs** [iobis/obis-network-datasets#203]
OBIS-USA was notified by Jon Fong at California Academy of Sciences that OBIS was added as a network to the [CAS Mammalogy collection](http://ipt.calacademy.org:8080/resource?r=mam) on 2022-11-30 but I have not seen this resource come into this repo. Trying to figure out where the disconnect may be.

**Comment by pieterprovoost** [comment]
I missed the fact that GitHub disables cron based actions if there are no commits for 60 days :neutral_face: Fixed now.
