### ISSUE TITLE
Existing EurOBIS picked up

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/obis-network-datasets#430]
A number of EurOBIS datasets have been added here, possibly due to encoding issues and/or http(s).

- https://github.com/iobis/obis-network-datasets/issues/422
- https://github.com/iobis/obis-network-datasets/issues/423
- https://github.com/iobis/obis-network-datasets/issues/424
- https://github.com/iobis/obis-network-datasets/issues/425
- https://github.com/iobis/obis-network-datasets/issues/426
- https://github.com/iobis/obis-network-datasets/issues/427
- https://github.com/iobis/obis-network-datasets/issues/428
- https://github.com/iobis/obis-network-datasets/issues/429

**Comment by rubenpp7** [comment]
Hi @pieterprovoost ,

Thanks for reporting, I'll check what went wrong, I only registered in GBIF them and added the OBIS network to them so I am not really sure what happened yet.

Cheers

**Comment by pieterprovoost** [comment]
@rubenpp7 I think the issue was on our end, I'll do a bit more testing and then reenable the periodic check.

**Comment by bart-v** [comment]
The GBIF UUID is clearly included in the EurOBIS IPT
i.e. for https://ipt.vliz.be/eurobis/resource?r=dasid_6506#anchor-additional
the UUID `86c2fe69-e899-4223-aa45-355adad135f5` is clearly listed

**Comment by pieterprovoost** [comment]
@bart-v The question was about OBIS UK datasets which do not have GBIF UUIDs on your IPT, for example https://www.dassh.ac.uk/ipt/resource?r=dasshdt00000071 versus https://ipt.vliz.be/eurobis/resource?r=dasshdt00000071. Yes, in this case I could use the DOI to make the connection (which at DASSH is nicely part of the alternate identifiers but no longer at EurOBIS), but I still think there should be a provenance trail back to the original version on the DASSH IPT (FAIR principles R1.2).

Also notice the differences in title and abstract.

**Comment by bart-v** [comment]
OK, @rubenpp7 can you make sure to include the DASSH URL and DOI in IMIS?
