### ISSUE TITLE
eDNA from water column to characterise fish and invertebrate communities from 30 sites in the Belgian Part of the North Sea -COI

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/obis-network-datasets#461]
- title: eDNA from water column to characterise fish and invertebrate communities
    from 30 sites in the Belgian Part of the North Sea -COI
- GBIF: https://www.gbif.org/dataset/652ac1af-3907-4fd3-a509-2151a00bccc2
- created: '2024-03-28T13:38:05.302+00:00'
- URLs:
  - 652ac1af-3907-4fd3-a509-2151a00bccc2
  - https://ipt.inbo.be/resource?r=ilvo-metabarcoding-coi-bpns
  - https://doi.org/10.15468/tvng39

**Comment by Kydae** [comment]
I'm looking at the datasets that have the label 'node: EurOBIS' to start the harvest. I made a QC check and here are the results (I put it here, so it's documented, and I can keep track of what have already been done).
![image](https://github.com/iobis/obis-network-datasets/assets/118560141/44041523-278d-434a-bcf1-c1733c6965a5)
