### ISSUE TITLE
eDNA from water column to characterise fish and invertebrate communities from 30 sites in the Belgian Part of the North Sea -12S

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/obis-network-datasets#462]
- title: eDNA from water column to characterise fish and invertebrate communities
    from 30 sites in the Belgian Part of the North Sea -12S
- GBIF: https://www.gbif.org/dataset/8fd84a4f-bbed-490b-9ca4-c0a3d0aea079
- created: '2024-03-28T13:04:36.953+00:00'
- URLs:
  - 8fd84a4f-bbed-490b-9ca4-c0a3d0aea079
  - https://ipt.inbo.be/resource?r=ilvo-metabarcoding-12s-bpns
  - https://doi.org/10.15468/nvabg3

**Comment by Kydae** [comment]
I'm looking at the datasets that have the label 'node: EurOBIS' to start the harvest. I made a QC check and here are the results (I put it here, so it's documented, and I can keep track of what have already been done).
![image](https://github.com/iobis/obis-network-datasets/assets/118560141/eb781446-a0a7-49b1-b9cf-d023cde09101)
