### ISSUE TITLE
Vertical and horizontal environmental DNA (eDNA) patterns of fish in a shallow and well-mixed North Sea area

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/obis-network-datasets#463]
- title: Vertical and horizontal environmental DNA (eDNA) patterns of fish in a shallow
    and well-mixed North Sea area
- GBIF: https://www.gbif.org/dataset/8afcc57c-5d2b-4349-add6-29bfc33ed5cb
- created: '2024-03-28T10:59:13.499+00:00'
- URLs:
  - 8afcc57c-5d2b-4349-add6-29bfc33ed5cb
  - https://ipt.inbo.be/resource?r=ilvo-metabarcoding-1
  - https://doi.org/10.15468/3ygzac

**Comment by Kydae** [comment]
I'm looking at the datasets that have the label 'node: EurOBIS' to start the harvest. I made a QC check and here are the results (I put it here, so it's documented, and I can keep track of what have already been done).
![image](https://github.com/iobis/obis-network-datasets/assets/118560141/162795dc-363b-4775-83f6-925e1daf2ba2)
