### ISSUE TITLE
Evaluación submareal de los bajos “EL ACUARIO” y “RABO DEL VIEJO” de la Reserva Marina El Pelado, Provincia de Santa Elena - 2023

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/obis-network-datasets#465]
- title: "Evaluaci\xF3n submareal de los bajos \u201CEL ACUARIO\u201D y \u201CRABO\
    \ DEL VIEJO\u201D de la Reserva Marina El Pelado, Provincia de Santa Elena - 2023"
- GBIF: https://www.gbif.org/dataset/3c9d0f3e-f49a-4176-9c67-04bb94faa954
- created: '2024-02-21T15:53:18.638+00:00'
- URLs:
  - http://patrimonio.ambiente.gob.ec/iptmae/resource?r=dwca-maate-arsfc-2023-3179
  - https://doi.org/10.60545/xixnti

**Comment by vechocho** [comment]
@pieterprovoost Ecuador

**Comment by vechocho** [comment]
@pieterprovoost This publisher has two profiles on Ocean Expert. both refer to the same University

https://oceanexpert.org/institution/19093
https://oceanexpert.org/institution/24154
