### ISSUE TITLE
FKt230918 expedition – Vertical Reef of the Galapagos

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/obis-network-datasets#474]
- title: "FKt230918 expedition \u2013 Vertical Reef of the Galapagos"
- GBIF: https://www.gbif.org/dataset/2a796aad-0c69-4f08-a207-f216cc75b466
- created: '2024-08-20T13:07:11.903+00:00'
- URLs:
  - https://patrimonio.ambiente.gob.ec/iptmae/resource?r=047ea0b6-6d01-4431-8e78-9fb43d51ee8d
  - https://doi.org/10.60545/cz8ams

**Comment by vechocho** [comment]
IDK if this is the place to ask. 

How do I match a dataset to an institute? as this dataset is published by [Memorial University of Newfoundland](https://www.gbif.org/publisher/11fafc78-3da8-4ac8-8f8e-fc5af5de3d8e), but does not appear on the institution page on OBIS [Memorial University of Newfoundland](https://obis.org/institute/19340)

**Comment by vechocho** [comment]
@pieterprovoost I tag you as I can't reopen an issue. I think for follow up and update of publisher is better to do here on GitHub
