### ISSUE TITLE
BIGOOD

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/obis-network-datasets#489]
- title: BIGOOD
- GBIF: https://www.gbif.org/dataset/96309e26-f762-11e1-a439-00145eb45e9a
- created: '2009-02-24T08:49:45.000+00:00'
- URLs:
  - 10.15468/yxphxa
  - https://ipt.gbif.fr/resource?r=ifremer_bigood
  - 96309e26-f762-11e1-a439-00145eb45e9a
  - '8114'
  - https://doi.org/10.15468/dl.ey5ub5

**Comment by pieterprovoost** [comment]
In EurOBIS https://obis.org/dataset/b0a7add2-dd9e-4020-9ca4-5df048c8f6a2

**Comment by cyrilrader** [comment]
@pieterprovoost This dataset has been removed from the EurOBIS IPT since it's already present in another IPT. Can I ask you to change the IPT URL for https://obis.org/dataset/b0a7add2-dd9e-4020-9ca4-5df048c8f6a2 and add this IPT URL instead: https://ipt.gbif.fr/resource?r=ifremer_bigood ?
